server:
  port: 8021
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB     
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/FuneralMatching?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: sbsst
    password: sbs123414
mybatis:
  type-aliases-package: com.fm.backend.dto 
custom:
  genFileDirPath: C:/work/funeral-matching-file
  logging:
    dir: log
    level: debug    